### ISSUE TITLE
self:SetNormalTexture(asset) Error

### ISSUE THREAD

**Issue by nancikennedy** [DDCorkum/CTMod#137] opened 2022-10-28 20:16 UTC
Not sure what is causing this....

5x Usage: self:SetNormalTexture(asset)
[string "=[C]"]: in function `SetNormalTexture'
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:648: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:627>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:669: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:665>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:678: in function <Interface/AddOns/CT_Core/CT_Core_Chat.lua:674>
[string "@Interface/AddOns/CT_Core/CT_Core_Chat.lua"]:1214: in function `chatupdate'
[string "@Interface/AddOns/CT_Core/CT_Core.lua"]:234: in function `updateFunc'
[string "@Interface/AddOns/CT_Library/CT_Library.lua"]:978: in function `setOption'
[string "@Interface/AddOns/CT_Library/CT_Library.lua"]:1723: in function <Interface/AddOns/CT_Library/CT_Library.lua:1718>

Locals:
(*temporary) = "Usage: self:SetNormalTexture(asset)"

**Comment by DDCorkum** [comment] 2022-11-03 16:56
Thanks for the bug report.  It was caused by the method of hiding chat box draggable corners when you don't mouseover them.

This will be fixed in the next version.

**Closed** 2022-11-04 07:00 UTC
Labels: - Defect, CT_Core
