### ISSUE TITLE
Null barrier not following other buff settings

### ISSUE THREAD

**Issue by Castiana** [DDCorkum/CTMod#61] opened 2020-07-20 12:13 UTC
The Null Barrier buff is showing under "Uncancelable buffs" instead of regular buffs. There is no option to force it to display as a standard "cancelable" buff. I've also checked for a way to manually specify which category buffs fall under, but cannot find where to set it. Please see screenshots for a demonstration and Buff Settings.

Thanks for your time, and great mods! I've used CT since TBC. By far one of the most helpful mod's I've ever used!

Cheers,

![barrier](https://user-images.githubusercontent.com/1525334/87936462-c5bcbe00-ca8a-11ea-9bba-6fc4a1487661.png)
![buffsettings](https://user-images.githubusercontent.com/1525334/87936464-c6edeb00-ca8a-11ea-81bb-892f063a8b42.png)

**Comment by DDCorkum** [comment] 2020-07-20 23:45
I think this particular buff might be flagged as 'passive' in the game engine because it comes off the azerite essence, so in a way it is 'uncancellable' as long as you wear the item.  (By contrast, you can right-click to dismount so that is truly cancellable.)

I do see a problem though, that the traditional passives are not appearing above it despite your selection to display non-expiring buffs before others.   This should be something CT could do, since you've opted for insecure buff buttons.   I'll keep this issue on my todo list going into Shadowlands.

**Comment by DDCorkum** [comment] 2020-07-20 23:49
Update: this should be address concurrently with #55 .

The issue here is sorting, vice filtering, but really both problems have the same root.

**Comment by Castiana** [comment] 2020-07-21 09:41
Perfect, thank you for the update!

Keep up the great work.

Thanks for your time,

Cheers,

**Comment by DDCorkum** [comment] 2020-09-19 00:40
Update:  while doing #55 I discovered the problem is fundamentally a matter of which order the sort filters are applied in.   Right now, the aura type sort is considered before the duration/non-duration sort.   To solve this issue, I need to provide an option to choose the order that sort filters are applied in.

**Comment by DDCorkum** [comment] 2020-09-27 02:20
This will be fixed going into the Shadowlands prepatch.  Non-secure frames will have an option to choose the order that grouping/sorting filters are applied in.

**Closed** 2020-10-13 21:33 UTC
Labels: - Defect, Affects Retail, CT_BuffMod
