### ISSUE TITLE
Mage Teleport and Portal flyouts do flyout but no buttons react

### ISSUE THREAD

**Issue by ilmare-tuor** [DDCorkum/CTMod#147] opened 2022-12-18 00:38 UTC
With both 10.0.2.3b and 10.0.2.3d. Clicking on the main button on bar causes the flyout to open up but all the Teleports or Portals are "greyed out" and do not react to a mouse click.

**Comment by DDCorkum** [comment] 2022-12-18 09:59
Does this also happen immediately after you /reload ?

If it works after reload, but stops working while you are playing the game, then my main suspicion would be that I'm tainting the UI (somewhere) and it is somehow spreading.

If it also doesn't work after a fresh reload, then I'm actually a bit curious why I don't experience the same issue on my own mage.


Maybe the "greyed out" might be a clue.  Can you send me a screenshot of what the buttons look like, exactly, so I get a sense of what you mean?  I'll try fiddling with my UI to recreate the same appearance, and see if I can find a common thread.

**Comment by ilmare-tuor** [comment] 2022-12-18 17:53
![TeleportFlyoutGrey](https://user-images.githubusercontent.com/115592404/208311099-21862432-e1ce-432b-94d3-c77a8e75df19.jpg)

/reload has no affect.

1) It always works from within the spellbook
2) Toggling "CT_BarMod" (with a reload) toggles whether it works or not from the bar. 

So with CT_ BarMod ON it works from spellbook but not from bar (I tried both "action bar" and other bars). With CT_ BarMod OFF it works fine from the bar.

It works this way with all addons disabled except for CT_Library and toggling CT_ BarMod

I also renamed my WTF folder to make sure it wasn't some saved variable causing the issue.

Hope this helps

**Comment by DDCorkum** [comment] 2022-12-26 10:01
I made a couple small changes to 10.0.2.4d that may or may not solve the issue.   At the least, it should remove the "washed out" appearance.

**Comment by ilmare-tuor** [comment] 2022-12-27 00:23
I installed 10.0.2.4d and the only change I saw was the elimination of the "washed out" appearance so I started poking around other settings.

Under BarMod I toggled the "Toggle Action Key Up/Down so it "currently responds to _mouse up_ & _key up_" and it fixed the issue. Toggling back to "_mouse down_ & _key down_" breaks it again.

I only spent a few minutes poking around with other functions but, I don't appear to have any other issues so I'll just leave them set for "up"

**Comment by DDCorkum** [comment] 2022-12-27 08:36
Oh, good find.   Now I understand what the issue is.  This will be fixed shortly.

Details:  Blizzard changed how secure action buttons respond to mouse clicks this expansion, to prevent addons from automating the new Dracthyr empowered spells (press and hold for a while).  It's actually a good design, in my opinion, but requires an extra line of code for compatibility.  I just forgot that extra line of code.

**Comment by ilmare-tuor** [comment] 2022-12-27 21:17
Awesome. Thanks for all your work fixing this stuff!

**Closed** 2022-12-28 08:31 UTC
Labels: - Defect, Affects Retail, CT_BarMod
